### PR TITLE
Wicket Bootstrap Spring Boot Quickstart

### PR DESCRIPTION
**Pull request by ageery**
A getting started guide for using Spring Boot with Wicket and Twitter Bootstrap.

### CODE REVIEW

**Comment by ageery** [comment]
Any comments or feedback on this guide?

Thanks
Andrew

**Comment by gregturn** [comment]
Sorry I haven't found time to check out your guide. I have a stack of guide related tasks accumulating and when I find a break from my other responsibilities, I can circle back to evaluate it.

**Comment by gregturn** [comment]
I believe at this point in time, we cannot in good faith take on this guide and ensure its maintenance. Sorry.

**Comment by pivotal-issuemaster** [comment]
@ageery Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/getting-started-guides&pullRequestId=17)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/getting-started-guides&pullRequestId=17) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Pull request closed without merging**
