### PR TITLE
Adding new Azure-related articles

### PR DESCRIPTION
**Pull request by rmcmurray**

### CODE REVIEW

**Comment by gregturn** [comment]
@rmcmurray I took your branch, did some polishing in my own fork, and submitted a PR to your branch. If you could check it out, merge it, then squash and rebase your branch, we can proceed to publish this guide.

**Comment by rmcmurray** [comment]
Thanks @gregturn, I'll look into that today.

**Comment by gregturn** [comment]
That's because on guides, only one page is rendered, the README.adoc.

A "project page" is hosted based on a repo at github.com/spring-projects or github.com/spring-cloud, on the respective gh-pages branch. The material you drafted would go there, but I'm not sure what project we're talking about to host this.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/gs-spring-boot-for-azure/commit/1a674d8e57da015c428d387047f33160ef7c8a58

**Pull request closed without merging**
