### PR TITLE
WIP: Create A Guide For HATEOS with Kotlin and Coroutines

### PR DESCRIPTION
**Pull request by marzelwidmer**
Idea for a Spring Guide about Kotlin with Coroutine for a HATEOAS API.

https://github.com/spring-guides/getting-started-guides/issues/135

### CODE REVIEW

**Comment by Buzzardo** [comment]
We love that you want to make a new guide. However, we don't accept commits directly to master for a new guide. We have a process that lets us evaluate the guide. Also, we have an automated system that relies on naming conventions. Please read https://github.com/spring-guides/getting-started-guides/wiki (including the links at the bottom).

One of those links goes to https://github.com/spring-guides/getting-started-guides/wiki/Create-a-Repository. It says to create a new repository named `draft-gs-name-of-your-guide`. Please create that repository, add this content to it, and make a PR for it to https://github.com/spring-guides/getting-started-guides (since you have an issue, please attach the PR to that issue).

We're not trying put you off, but we have a definite process that we need to follow for creating a new guide.

Thanks a bunch.

**Comment by marzelwidmer** [comment]
@Buzzardo  thank then this process here is not valid anymore :) https://www.youtube.com/watch?v=Gby5xx2BxyI I will get back to you guys thanks.

**Comment by Buzzardo** [comment]
I had no idea that even existed. Sorry it led you down a wrong path. I'll drop a note on that video to let folks know it's outdated. Thanks again.

**Comment by marzelwidmer** [comment]
@Buzzardo  I try it again :) hope to get it right :) now...

**Comment by marzelwidmer** [comment]
Hello can I have maybe some support…..

I try to check https://github.com/spring-guides/getting-started-guides/pull/137 <https://github.com/spring-guides/getting-started-guides/pull/137>

with sagan project
guides:
  owner:
    name: ${GITHUB_GUIDES_OWNER_NAME:marzelwidmer}
    type: ${GITHUB_GUIDES_OWNER_TYPE:users}

**Comment by Buzzardo** [comment]
@gregturn knows this process well. Maybe he can help.

**Pull request closed without merging**
