### PR TITLE
GSG for Spring Cloud Netflix Zuul

### PR DESCRIPTION
**Pull request by fifthposition**
Shows how to use Netflix Zuul for routing and filtering.

### CODE REVIEW

**Comment by dsyer** [comment]
This looks awesome. The only issue I foresee is that STS (and maybe other tools) make assumptions about the structure of the project. I think there are other guides that do not simply have a single maven/gradle project under /complete, so this one might not be a complete outlier.

In any case the top level of the complete project looks like it is trying to build a jar which must be wrong (it should be a pom with a reactor build for the subprojects).

**Comment by gregturn** [comment]
@fifthposition If you throw out the top level build.gradle, and adjust the top level pom.xml to look like this => https://github.com/spring-guides/gs-service-registration-and-discovery/blob/master/complete/pom.xml, it should work.

See https://github.com/spring-guides/gs-service-registration-and-discovery/tree/master/complete as your template for a multi-module guide.

**Comment by gregturn** [comment]
To further test things, run test/run.sh on the root of the project. We do that for all Travis CI jobs. It will give you hints if anything is out of alignment.

**Comment by fifthposition** [comment]
@dsyer @gregturn Thank you! The POM now builds the subprojects and the `complete/build.gradle` is gone. (And thanks for pointing out `test/run.sh`!).

**Comment by dsyer** [comment]
We need a `build.gradle` as well don't we?

**Comment by gregturn** [comment]
@dsyer Apparently not. See the registry guide. It works fine as is.

**Comment by dsyer** [comment]
But if anyone wants to use this as a project template and they want to use gradle, won't they expect it? I guess we can skip it for now if there's a precedent.

**Comment by gregturn** [comment]
@dsyer gradle works. test/run.sh verifies it.

**Comment by gregturn** [comment]
It has settings.gradle which tells it what to do.

**Comment by gregturn** [comment]
Successfully merged into https://github.com/spring-guides/gs-routing-and-filtering

**Pull request closed without merging**
