### PR TITLE
GSG for Spring Cloud Netflix Hystrix

### PR DESCRIPTION
**Pull request by fifthposition**
Doesn’t show the Hystrix Dashboard—just Hystrix (wasn’t sure whether including the Dashboard might make it a bit lengthy).

### CODE REVIEW

**Comment by gregturn** [comment]
Based on https://spring.io/admin/projects, I'd put in spring-cloud-netflix as a project tag.

**Comment by fifthposition** [comment]
@gregturn Done! :smiley:

**Comment by dsyer** [comment]
Is this superseded by https://github.com/spring-guides/gs-circuit-breaker?

**Comment by gregturn** [comment]
Yes

**Pull request closed without merging**
